SELECT * FROM EMP_SS66 WHERE JOB  = 'Manager' ;
SELECT * FROM EMP_SS66 WHERE EMPNO = 7369;
SELECT * FROM EMP_SS66 WHERE HIREDATE = '01-MAY-81';
SELECT * FROM EMP_SS66 WHERE SAL > 1500;
SELECT * FROM EMP_SS66 WHERE COMM IS NULL;
SELECT * FROM EMP_SS66 WHERE ENAME LIKE 'A%';
ALTER TABLE EMP_SS66 ADD (PHONE_NO VARCHAR (15));
ALTER TABLE EMP_SS66 MODIFY (JOB VARCHAR2 (20));
ALTER TABLE EMP_SS66 DROP COLUMN PHONE_NO;
